version: "3.7"

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: fanbrel/app:v1.0.0
    container_name: fanbrel-fanbrel_app
    restart: on-failure:10
    stop_grace_period: 1m
    ports:
      - "3500:3500"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /sys/class/thermal/thermal_zone0:/sys/class/thermal/thermal_zone0:ro
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      default:
        ipv4_address: 10.21.21.10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fanbrel-fanbrel.entrypoints=web"
      - "traefik.http.routers.fanbrel-fanbrel.rule=PathPrefix(`/`)"
      - "traefik.http.services.fanbrel-fanbrel.loadbalancer.server.port=3500"

networks:
  default:
    name: fanbrel-fanbrel_default
    ipam:
      config:
        - subnet: 10.21.21.0/24 