version: "3.7"

services:
  app:
    image: fanbrel/app:v1.0.0
    build: 
      context: ../app
      dockerfile: Dockerfile
    restart: on-failure:10
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /sys/class/thermal/thermal_zone0:/sys/class/thermal/thermal_zone0:ro
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - ${APP_FANBREL_PORT:-3500}:3500
    networks:
      default:
        ipv4_address: 10.21.21.10

  app_proxy:
    image: nginx:1.25.3-alpine
    restart: on-failure:10
    environment:
      - PROXY_AUTH_ADD=true
      - APP_HOST=app
      - APP_PORT=3500
      - PROXY_AUTH_WHITELIST=/api/*
    volumes:
      - ${APP_DATA_DIR}/nginx:/etc/nginx
    depends_on:
      - app
    networks:
      default:
        ipv4_address: 10.21.21.11

networks:
  default:
    name: fanbrel-fanbrel_default
    ipam:
      config:
        - subnet: 10.21.21.0/24 